# Generated by Django 4.1 on 2022-08-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_user_patronymic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Отчество'),
            preserve_default=False,
        ),
    ]
